x-base: &base
  build:
    context: .
    dockerfile: ./Dockerfile
    args:
      RUBY_VERSION: '3.4.1'
  stdin_open: true
  tty: true
  volumes:
    - .:/app

services:
  app:
    <<: *base
    command: rails s -b 0.0.0.0
    ports:
      - '3000:3000'
    env_file:
      - .env